<div class="navbar">
      <div class="navbar-inner">
        <div class="container-fluid">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href="/">Openovate Forums</a>
          <div class="nav-collapse collapse">
            <p class="navbar-text pull-right">
            	<?php if (isset($_SESSION['uid'])):?>
              <img src='/assets/uploads/<?=$_SESSION["user_picture"]?>' width='50' height='50'>
              Logged in as <?=$_SESSION['name'] ?> <a href="/?logout=1" class="navbar-link">	(Logout) </a>
              	<?php else: ?>
              <a href="/login" class="navbar-link">Sign Up </a>
              	<?php endif; ?>
            </p>
            <ul class="nav">
               <li><a href="http://www.openovate.com">Home</a></li>
               <li><a href="http://eden.openovate.com">Eden PHP</a></li>
               <li><a href="http://www.openovate.com/#about" class="link-about">About</a></li>
               <li><a href="http://www.openovate.com/#client" class="link-client">Clients</a></li>
               <li><a href="http://www.openovate.com/#team" class="link-team">Team</a></li>
               <li><a href="http://www.openovate.com/#contact" class="link-contact">Contact</a></li>
               <li><a href="http://www.openovate.com/startup" class="link-blog">Blog</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>