<div class="navbar">
      <div class="navbar-inner">
        <div class="container-fluid">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href="/">Openovate Forums</a>
          <div class="nav-collapse collapse">
            <p class="navbar-text pull-right">
            	<?php if (isset($_SESSION['uid'])):?>
              Logged in as <?=$_SESSION['name'] ?> <a href="/?logout=1" class="navbar-link">	Logout </a>
              	<?php else: ?>
              <a href="/login" class="navbar-link">Sign Up </a>
              	<?php endif; ?>
            </p>
            <ul class="nav">
              <li class=""><a href="/">Topics</a></li>
              <li><a href="#about">About</a></li>
              <li><a href="#contact">Contact</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>