<!DOCTYPE html>
<html class="<?php print $class; ?>">
	
<head>
	<title><?php print $title; ?></title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	
	<?php if(isset($meta) && is_array($meta)): ?>
    <?php foreach($meta as $name => $content): ?>
    <meta name="<?php print $name; ?>" content="<?php print $content; ?>" />
    <?php endforeach; ?>
    <?php endif; ?>

    <link rel="stylesheet" type="text/css" media="screen" href="/assets/styles/bootstrap.css" />
    <link rel="stylesheet" type="text/css" media="screen" href="/assets/styles/mystyle.css" />
	<link rel="stylesheet" type="text/css" media="screen" href="/assets/styles/bootstrap-responsive.css" />
	<link rel="stylesheet" type="text/css" media="screen" href="/assets/styles/bootstrap-fileupload.css" />
	<link rel="stylesheet" type="text/css" media="screen" href="/assets/styles/jquery.fileupload-ui.css" />
		<link rel="stylesheet" type="text/css" media="screen" href="/assets/styles/social-buttons.css" />

</head>

<body>
	<div class="page">
		<div class="head"><?php echo $head; ?></div>
		<div class="body"><?php echo $body; ?></div>
		<div class="foot"><?php echo $foot; ?></div>
		<script type="text/javascript" src="/assets/scripts/jquery.js"></script>
		<script type="text/javascript" src="/assets/scripts/main.js"></script>
		<script type="text/javascript" src="/assets/scripts/validate.js"></script>
		<script type="text/javascript" src="/assets/scripts/bootstrap-button.js"></script>
		<script type="text/javascript" src="/assets/scripts/bootstrap-collapse.js"></script>
		<script type="text/javascript" src="/assets/scripts/bootstrap-fileupload.js"></script>
		<script type="text/javascript" src="/assets/scripts/jquery.form.js"></script>
		<script type="text/javascript" src="/assets/scripts/bootstrap-alert.js"></script>
    </div>
</body>
</html>
