
<div class="container">

	<div class="well">
		<div class="row-fluid">
			<DIV class='span6'>
				<form id="login" name="login" class="form-horizontal" method="post">
				<legend>Login</legend>
				<div class="control-group">
						<?=$loginerrors?>
				</div>
				<div class="control-group">
					 <label class="control-label">Email</label>
					 <div class="controls">
					    <div class="input-prepend">
						<span class="add-on"><i class="icon-envelope"></i></span>
							<input type="text" class="input-xlarge field" id="loginemail" name="loginemail" placeholder="Email">
						</div>
					</div>
				</div>
				<div class="control-group">
					 <label class="control-label">Password</label>
					 <div class="controls">
					    <div class="input-prepend">
						<span class="add-on"><i class="icon-lock"></i></span>
							<input type="password" class="input-xlarge field" id="loginpassword" name="loginpassword" placeholder="Password">
						</div>
					</div>
				</div>
				<div class="control-group">
				<label class="control-label"></label>
			      <div class="controls">
			      	 <!-- <div class="input-prepend"> -->
			      	 	<!-- <span class="add-on"><i class=" icon-arrow-right"></i></span></div>  -->
			       		<button type="submit" class="btn btn-success login" ><span class="IL_AD" id="IL_AD4">Login</span></button>
			      	 
			       </div>
			   	 </div>
			   	 
				</form>
			</DIV>
			<div class="span6">
	      		<form class="form-horizontal" id='signup' name='signup' method="POST"  enctype="multipart/form-data">
    				<fieldset>
   						<div id="legend">
   						<legend class="">Register</legend>
    					</div>
    				<div class="control-group">
						<?=$signerrors?>
					</div>
					<div class="control-group">
						<label class="control-label" for="firstname">Avatar</label>
						<div class="controls">
							<div class="fileupload fileupload-new" data-provides="fileupload">
							<div class="input-append">
							<div class="uneditable-input"><i class="icon-file fileupload-exists"></i> <span class="fileupload-preview"></span></div><span class="btn btn-file"><span class="fileupload-new">Select file</span><span class="fileupload-exists">Change</span><input type="file" name="myFile"/></span><a href="#" class="btn fileupload-exists" data-dismiss="fileupload">Remove</a>
							</div>
							</div>
							<p class="help-block">Image files only.</p>
					    </div>
    				</div>
   					<div class="control-group">
					   	<label class="control-label" for="firstname">Firstname: *</label>
					    <div class="controls">
					    	<input type="text" id="firstname" name="firstname" placeholder="" class="input-xlarge">
					    </div>
    				</div>
     				<div class="control-group">
					   	<label class="control-label" for="lastname">Lastname:*</label>
					    <div class="controls">
					    	<input type="text" id="lastname" name="lastname" placeholder="" class="input-xlarge">
					    </div>
    				</div>
				    <div class="control-group">
					    <label class="control-label" for="email">E-mail:*</label>
					    <div class="controls">
						    <input type="text" id="email" name="email" placeholder="" class="input-xlarge">
					    </div>
				    </div>
				    <div class="control-group">
					    <label class="control-label" for="password">Password:*</label>
					    <div class="controls">
						    <input type="password" id="password" name="password" placeholder="" class="input-xlarge">
						    <p class="help-block">Password should be at least 6 characters</p>
					    </div>
				    </div>
     
				    <div class="control-group">
					    <label class="control-label" for="cpassword">Confirm Password:*</label>
					    <div class="controls">
					    	<input type="password" id="cpassword" name="cpassword" placeholder="" class="input-xlarge">
					    	<p class="help-block">Please confirm password</p>
					    </div>
				    </div>
     
				    <div class="control-group">
					    <div class="controls">
					   	 <button class="btn btn-success">Register</button>
					    </div>
				    </div>
    			</fieldset>
   			 </form>
		  </div>

	</div>
   </div>
</div>