
<div class="container">

	<div class="well">
		<div class="row-fluid">
			<DIV class='span6'>
				<form id="login" name="login" class="form-horizontal" method="post">
				<legend>Login</legend>
				<div class="control-group">
					<?php if (isset($loginerrors)):?>
					<div class="error_box alert alert-error">

					</div>
					<?php endif; ?>
				</div>
				<div class="control-group">
					 <label class="control-label">Email</label>
					 <div class="controls">
					    <div class="input-prepend">
						<span class="add-on"><i class="icon-envelope"></i></span>
							<input type="text" class="input-xlarge field" id="loginemail" name="loginemail" placeholder="Email">
						</div>
					</div>
				</div>
				<div class="control-group">
					 <label class="control-label">Password</label>
					 <div class="controls">
					    <div class="input-prepend">
						<span class="add-on"><i class="icon-lock"></i></span>
							<input type="text" class="input-xlarge field" id="loginpassword" name="loginpassword" placeholder="Password">
						</div>
					</div>
				</div>
				<div class="control-group">
				<label class="control-label"></label>
			      <div class="controls">
			      	 <!-- <div class="input-prepend"> -->
			      	 	<!-- <span class="add-on"><i class=" icon-arrow-right"></i></span></div>  -->
			       		<button type="submit" class="btn btn-success login" ><span class="IL_AD" id="IL_AD4">Login</span></button>
			      	 
			       </div>
			   	 </div>
			   	 
				</form>
			</DIV>
			<div class="span6">
	      		<form class="form-horizontal" id='signup' name='signup' method="POST">
    				<fieldset>
   						<div id="legend">
   						<legend class="">Register</legend>
    					</div>
    				<div class="control-group">
						<div class="error_box1 alert alert-error">
						</div>
					</div>
   					<div class="control-group">
					   	<label class="control-label" for="firstname">Firstname</label>
					    <div class="controls">
					    	<input type="text" id="firstname" name="firstname" placeholder="" class="input-xlarge">
					    </div>
    				</div>
     				<div class="control-group">
					   	<label class="control-label" for="lastname">Lastname</label>
					    <div class="controls">
					    	<input type="text" id="lastname" name="lastname" placeholder="" class="input-xlarge">
					    </div>
    				</div>
				    <div class="control-group">
					    <label class="control-label" for="email">E-mail</label>
					    <div class="controls">
						    <input type="text" id="email" name="email" placeholder="" class="input-xlarge">
					    </div>
				    </div>
				    <div class="control-group">
					    <label class="control-label" for="password">Password</label>
					    <div class="controls">
						    <input type="password" id="password" name="password" placeholder="" class="input-xlarge">
						    <p class="help-block">Password should be at least 6 characters</p>
					    </div>
				    </div>
     
				    <div class="control-group">
					    <label class="control-label" for="cpassword">Password (Confirm)</label>
					    <div class="controls">
					    	<input type="password" id="cpassword" name="cpassword" placeholder="" class="input-xlarge">
					    	<p class="help-block">Please confirm password</p>
					    </div>
				    </div>
     
				    <div class="control-group">
					    <div class="controls">
					   	 <button class="btn btn-success">Register</button>
					    </div>
				    </div>
    			</fieldset>
   			 </form>
		  </div>

	</div>
   </div>
</div>